name: Build

on:
  push:
    paths:
      - 'SimpleVoiceroid2Proxy/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: MSBuild
        run: msbuild SimpleVoiceroid2Proxy.sln -property:Configuration="Release" -property:Platform="Any CPU" -m -restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SimpleVoiceroid2Proxy
          if-no-files-found: error
          path: SimpleVoiceroid2Proxy/bin/Release

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path SimpleVoiceroid2Proxy/bin/Release/* -DestinationPath SimpleVoiceroid2Proxy.zip

      - name: Upload Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SimpleVoiceroid2Proxy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
