name: Build

on:
  push:
    paths:
      - 'SimpleVoiceroid2Proxy/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: MSBuild
        run: msbuild SimpleVoiceroid2Proxy.sln -property:Configuration="Release" -property:Platform="Any CPU" -m -restore

      - name: Upload Artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: SimpleVoiceroid2Proxy
          if-no-files-found: error
          path: SimpleVoiceroid2Proxy/bin/Release

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path SimpleVoiceroid2Proxy/bin/Release/* -DestinationPath SimpleVoiceroid2Proxy.zip

      - name: Upload Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SimpleVoiceroid2Proxy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
